window.MOVIES = [
  {
    "movie_title": "Arco",
    "original_title": "Arco",
    "original_language": "fr",
    "director": "Ugo Bienvenu",
    "cast": null,
    "genre": "Animation, aventure, SF",
    "duration": "1h28",
    "blurb": "En 2075, une petite fille de 10 ans, Iris, voit un mystérieux garçon vêtu d'une combinaison arc-en-ciel tomber du ciel. C'est Arco. Il vient d'un futur lointain et idyllique où voyager dans le temps est possible. Iris le recueille et va l'aider par tous les moyens à rentrer chez lui. Une aventure lumineuse, poétique, un voyage haut en couleur, présenté à Cannes et récompensé au festival d'Annecy où animation et science-fiction font bon ménage. Quand Miyazaki rencontre Steven Spielberg. Une vraie merveille !",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=e4RrOe8IbI8",
    "release_date": "2025-10-22",
    "poster_url": "https://image.tmdb.org/t/p/w342/rWvbMnqLTpyTHmNii4TrnmgzpcS.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/rWvbMnqLTpyTHmNii4TrnmgzpcS.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/jFKbhV0uFZuA3K73UJIq1dzisCi.jpg"
  },
  {
    "movie_title": "Chasse gardée 2",
    "original_title": "Chasse gardée 2",
    "original_language": "fr",
    "director": "Antonin Fourlon &amp; Frédéric Forestier",
    "cast": "Didier Bourdon, Camille Lou, Thierry Lhermitte, Hakim Jemini, Chantal Ladesou",
    "genre": "Comédie",
    "duration": "1h38",
    "blurb": "AVANT PREMIÈRE À CHATEAU-CHINON LE DIM-O7 DÉC. À 16h00 Deux ans se sont écoulés à Saint-Hubert. La vie y est paisible, peut-être trop pour Adélaïde et Simon qui souffrent du manque d'amis. C'est sans compter sur l'arrivée de Stanislas, le fils de Bernard (l'ancien président des chasseurs), qui revient vivre à la campagne avec sa femme et ses deux enfants. Ils sont beaux, jeunes, et sympas. Leur seul défaut : ils pratiquent la chasse à courre !",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=kHXjJ0VaOCA",
    "release_date": "2025-12-10",
    "poster_url": "https://image.tmdb.org/t/p/w342/9PJrHGp41hRTq2kkPWU2j6zzjat.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/9PJrHGp41hRTq2kkPWU2j6zzjat.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/nABJiQaUieY63EYueemftxCSK2j.jpg"
  },
  {
    "movie_title": "Chasse gardée 2 - AVP",
    "original_title": null,
    "original_language": null,
    "director": "Antonin Fourlon &amp; Frédéric Forestier",
    "cast": "Didier Bourdon, Camille Lou, Thierry Lhermitte, Hakim Jemini, Chantal Ladesou",
    "genre": "Comédie",
    "duration": "1h38",
    "blurb": "AVANT PREMIÈRE À CHATEAU-CHINON LE DIM-O7 DÉC. À 16h00 Deux ans se sont écoulés à Saint-Hubert. La vie y est paisible, peut-être trop pour Adélaïde et Simon qui souffrent du manque d'amis. C'est sans compter sur l'arrivée de Stanislas, le fils de Bernard (l'ancien président des chasseurs), qui revient vivre à la campagne avec sa femme et ses deux enfants. Ils sont beaux, jeunes, et sympas. Leur seul défaut : ils pratiquent la chasse à courre !",
    "source": "pdf",
    "yt_trailer_url": null,
    "release_date": null,
    "poster_url": null,
    "poster_url_w780": null,
    "backdrop_url": null
  },
  {
    "movie_title": "Deburau",
    "original_title": "Deburau",
    "original_language": "fr",
    "director": "Sacha Guitry",
    "cast": null,
    "genre": null,
    "duration": null,
    "blurb": "Avec Jeanne Fusier-Gir, Lana Marconi, Sacha Guitry - 1951 - Comédie dramatique - 1h35 Deburau est un mime reconnu qui rencontre un immense succès. Une de ses admiratrices, du nom de Marie, le fait succomber à son charme mais celle-ci n'est pas femme d'un seul homme... Le cœur brisé, il va consacrer sa vie à enseigner tout son art à son fils qui souhaite devenir son successeur au théâtre. Sacha Guitry rend hommage au mime Deburau, immortalisé par Jean-Louis Barrault dans «Les Enfants du Paradis», et en profite pour faire un éloge du spectacle et de la transmission. Séance présentée par William Robin, directeur de Sceni Qua Non.",
    "source": "pdf",
    "yt_trailer_url": null,
    "release_date": "1951-06-29",
    "poster_url": "https://image.tmdb.org/t/p/w342/g3QGKEu2RLIm1YeBWjIaxJU4Hy9.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/g3QGKEu2RLIm1YeBWjIaxJU4Hy9.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/eb7K3Tpfe8KsZ1Ffy4au8sp8xyL.jpg"
  },
  {
    "movie_title": "Deux procureurs",
    "original_title": "Zwei Staatsanwälte",
    "original_language": "ru",
    "director": "Sergei Loznitsa",
    "cast": "Aleksandr Kuznetsov, Aleksandr Filippenko",
    "genre": "Drame historique",
    "duration": "1h58",
    "blurb": "Union Soviétique, 1937. Des milliers de lettres de détenus accusés à tort par le régime sont brûlées dans une cellule de prison. Contre toute attente, l'une d'entre elles arrive à destination, sur le bureau du procureur local fraîchement nommé, Alexander Kornev. Il se démène alors pour rencontrer le prisonnier, victime d'agents de la police secrète, le NKVD. Prix François Chalais - Cannes 2025",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=AoZpxL2rI2M",
    "release_date": "2025-10-03",
    "poster_url": "https://image.tmdb.org/t/p/w342/iycYd9P7wyw6Oib2fpXZjfqxId3.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/iycYd9P7wyw6Oib2fpXZjfqxId3.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/3IZPY1mCgAKJTCvGVJv9ufyUz2f.jpg"
  },
  {
    "movie_title": "Dossier 137",
    "original_title": "Dossier 137",
    "original_language": "fr",
    "director": "Dominik Moll",
    "cast": "Léa Drucker, Guslagie Malanda",
    "genre": "Policier",
    "duration": "1h55",
    "blurb": "Le dossier 137 est en apparence une affaire de plus pour Stéphanie, enquêtrice à l'IGPN, la police des polices. Une manifestation tendue, un jeune homme blessé par un tir de LBD, des circonstances à éclaircir pour établir une responsabilité... Mais un élément inattendu va troubler Stéphanie, pour qui le dossier 137 devient autre chose qu'un simple numéro. Sélection officielle - Cannes 2025",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=Ll17lAq0MWY",
    "release_date": "2025-11-19",
    "poster_url": "https://image.tmdb.org/t/p/w342/frEovFFQ6CcGnAPmtLRAKRLoPa1.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/frEovFFQ6CcGnAPmtLRAKRLoPa1.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/kjKxmpuPIvXjDP4reWCkMaeK2Es.jpg"
  },
  {
    "movie_title": "Fous divers",
    "original_title": null,
    "original_language": null,
    "director": null,
    "cast": null,
    "genre": null,
    "duration": null,
    "blurb": null,
    "source": "tmdb",
    "yt_trailer_url": null,
    "release_date": null,
    "poster_url": null,
    "poster_url_w780": null,
    "backdrop_url": null
  },
  {
    "movie_title": "Imago",
    "original_title": "Imago",
    "original_language": "cs",
    "director": "Déni Oumar Pitsaev",
    "cast": null,
    "genre": "2025",
    "duration": "1h48",
    "blurb": "Déni est le nouveau propriétaire d'un petit lopin de terre dans une vallée isolée en Géorgie, à la frontière de la Tchétchénie dont il est exilé depuis l'enfance. Il débarque là-bas et projette d'y construire une maison qui tranche drôlement avec les coutumes locales. Un fantasme qui ravive ses souvenirs et ceux de son clan déraciné qui pourtant ne rêve que d'une chose, le marier ! Semaine Internationale de la Critique - Cannes 2025",
    "source": "pdf",
    "yt_trailer_url": null,
    "release_date": "1984-01-01",
    "poster_url": "https://image.tmdb.org/t/p/w342/oNjZd2eVpBffkOqKyg9XsHQpmIX.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/oNjZd2eVpBffkOqKyg9XsHQpmIX.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/kdijacY69QRmKg3PqbpcpE89OC9.jpg"
  },
  {
    "movie_title": "Jean Valjean",
    "original_title": "Jean Valjean",
    "original_language": "fr",
    "director": "Éric Besnard",
    "cast": "Bernard Campan, Grégory Gadebois, Isabelle Carré",
    "genre": "Drame",
    "duration": "1h38",
    "blurb": "1815. Jean Valjean sort du bagne, rejeté de tous. Errant, il trouve refuge chez un homme d'Église, sa sœur et leur servante. Face à cette main tendue, Jean Valjean vacille et, dans cette nuit suspendue, devra choisir qui il veut devenir. D'après l'œuvre « Les Misérables » de Victor Hugo.",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=X3SGsH2nFp8",
    "release_date": "2025-11-19",
    "poster_url": "https://image.tmdb.org/t/p/w342/gKfStbHwDEJgLJutv6abBQ3P1M1.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/gKfStbHwDEJgLJutv6abBQ3P1M1.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/nDOTcvuWFPrGROgba5BSn85OAxA.jpg"
  },
  {
    "movie_title": "L'inconnu de la grande Arche",
    "original_title": "L'Inconnu de la Grande Arche",
    "original_language": "fr",
    "director": "Stéphane Demoustier",
    "cast": "Claes Bang, Sidse Babett Knudsen, Swan Arlaud",
    "genre": "Drame",
    "duration": "1h46",
    "blurb": "1983, François Mitterrand décide de lancer un concours d'architecture international pour le projet phare de sa présidence : la Grande Arche de la Défense, dans l'axe du Louvre et de l'Arc de Triomphe ! A la surprise générale, Otto von Spreckelsen, architecte danois, remporte le concours. Film présenté à Un Certain Regard - Festival de Cannes 2025, adapté du roman La Grande Arche de Laurence Cossé publié en 2016.",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=br4gZkvwQps",
    "release_date": "2025-11-05",
    "poster_url": "https://image.tmdb.org/t/p/w342/54uFg7nfNYoN81dixlwRcNk9KGS.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/54uFg7nfNYoN81dixlwRcNk9KGS.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/mNqnqNtZlLRFm1VLc3YmLuuCwyI.jpg"
  },
  {
    "movie_title": "L'incroyable femme des neiges",
    "original_title": "L'Incroyable femme des neiges",
    "original_language": "fr",
    "director": "Sébastien Betbeder",
    "cast": "Blanche Gardin, Philippe Katerine, Bastien Bouillon",
    "genre": "Comédie dramatique",
    "duration": "1h42",
    "blurb": "Coline Morel, exploratrice du pôle Nord, voit sa vie partir à la dérive. Après des années passées à traquer ce yéti auquel elle est la seule à croire, elle se fait licencier et son compagnon la quitte. Coline n'a d'autre choix que de rentrer dans son village natal. Elle y retrouve ses deux frères, Biasile et Lolo, ainsi que son amour de jeunesse. Sélection Panorama - Berlin 2025 - Film tournée en région Bourgogne-Franche Comté.",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=DjBZmWtsqhY",
    "release_date": "2025-11-12",
    "poster_url": "https://image.tmdb.org/t/p/w342/7btcAVTca0cbXPXztWZKsKztz5X.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/7btcAVTca0cbXPXztWZKsKztz5X.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/mFpruC9PWsgxjqGC7kelia2bhUT.jpg"
  },
  {
    "movie_title": "L'étranger - 2h",
    "original_title": null,
    "original_language": null,
    "director": "François Ozon",
    "cast": "Benjamin Voisin, Rebecca Marder, Pierre Lottin",
    "genre": "Drame",
    "duration": "2h00",
    "blurb": "Alger, 1938. Meursault, modeste employé, enterre sa mère sans manifester la moindre émotion. Le lendemain, il entame une liaison avec Marie, une collègue de bureau. Son voisin, Raymond Sintès vient perturber son quotidien en l'entraînant dans des histoires louches jusqu'à un drame sur une plage, sous un soleil de plomb... Après le succès de son film «Quand vient l'automne», tourné dans la Nièvre, François Ozon revient avec un nouveau film, adapté du fameux roman d'Albert Camus : L'étranger.",
    "source": "pdf",
    "yt_trailer_url": null,
    "release_date": null,
    "poster_url": null,
    "poster_url_w780": null,
    "backdrop_url": null
  },
  {
    "movie_title": "La femme la plus riche du monde",
    "original_title": "La Femme la plus riche du monde",
    "original_language": "fr",
    "director": "Thierry Klifla",
    "cast": "Isabelle Huppert, Laurent Lafitte, Marina Foïs",
    "genre": "comédie",
    "duration": "2h03",
    "blurb": "Un film inspiré de l'histoire de Liliane Bettencourt, ce coup de foudre entre un écrivain photographe, ambitieux, insolent et la femme la plus riche du monde: sa beauté, son intelligence, son pouvoir. Rajoutez une héritière méfiante, un majordome aux aguets qui sait tout des secrets de famille : voilà une guerre où tous les coups sont permis ! Le réalisateur s'inspire de Françoise Bettencourt-Meyers, héritière du géant L'Oréal, et transpose dans une fiction contemporaine, les ressorts d'une tragédie classique, oscillant entre thriller psychologique, drame bourgeois et comédie. Drôle et absolument fascinant !",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=Cbvff_TBVfo",
    "release_date": "2025-10-29",
    "poster_url": "https://image.tmdb.org/t/p/w342/sxaMtiQLgUhMbvuSxNo5BZZ7EVs.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/sxaMtiQLgUhMbvuSxNo5BZZ7EVs.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/5qKiUPDrGOSmRKBlcpmY7OwPR0a.jpg"
  },
  {
    "movie_title": "La petite fanfare de Noel",
    "original_title": "La petite fanfare de Noël",
    "original_language": "fr",
    "director": "Meike Fehre &amp; Sabine Dully",
    "cast": null,
    "genre": "Animation, comédie, famille",
    "duration": "0h40",
    "blurb": "Au cœur de l'hiver, la neige recouvre tout. Quel silence ! Mais écoutez bien : dans ce grand calme blanc, mille sons vont bientôt éclore ! Un programme de 4 courts-métrages qui célèbre Noël et la musique !",
    "source": "pdf",
    "yt_trailer_url": null,
    "release_date": "2025-11-26",
    "poster_url": "https://image.tmdb.org/t/p/w342/ljCnKIG4kfMbKHRirUB9ZpnzJiY.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/ljCnKIG4kfMbKHRirUB9ZpnzJiY.jpg",
    "backdrop_url": null
  },
  {
    "movie_title": "La voix de Hind Rajab",
    "original_title": "صوت هند رجب",
    "original_language": "ar",
    "director": "Kaouther Ben Hania",
    "cast": "Amer Hlehel, Clara Khoury",
    "genre": "Drame",
    "duration": "1h29",
    "blurb": "29 janvier 2024. Les bénévoles du Croissant-Rouge reçoivent un appel d'urgence. Une fillette de six ans est piégée dans une voiture sous les tirs à Gaza. Tout en essayant de la garder en ligne, ils font tout leur possible pour lui envoyer une ambulance. Elle s'appelait Hind Rajab. Grand Prix du Jury - Venise 2025. Ce film représentera La Tunisie aux Oscars 2026 # ÉVÉNEMENTS",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=E5Fh-IZHtRo",
    "release_date": "2025-09-25",
    "poster_url": "https://image.tmdb.org/t/p/w342/vDXQUZOfXhhjpz7KMpL267ouyLU.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/vDXQUZOfXhhjpz7KMpL267ouyLU.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/mQwD7GtPTkv6WF5m8AJWGrO5XOE.jpg"
  },
  {
    "movie_title": "Le mariage de Verida",
    "original_title": "Flesh Out",
    "original_language": "fr",
    "director": "Michela Occhipinti",
    "cast": "Varida Beita Ahmed Deiche, Amal Saad Bouh Oumar",
    "genre": "Drame",
    "duration": "1h34",
    "blurb": "Verida est une jeune femme mauritanienne. Elle partage sa vie entre son travail d'esthéticienne et les sorties avec ses amies. Un matin, sa mère lui annonce qu'elle lui a trouvé un mari. Commence alors la tradition du gavage, on lui demande de prendre du poids pour plaire à son futur mari. Alors que le mariage approche, Verida a de plus en plus de mal à supporter cette nourriture en abondance, le changement de son corps et l'idée de se marier avec un homme qu'elle n'a pas choisi. Séance suivie d'un repas mauritanien et d'une présentation géopolitique de ce pays. Réservation repas à : luzyhospitalité@gmail.com",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=4XMHwJDu5tI",
    "release_date": "2019-05-04",
    "poster_url": "https://image.tmdb.org/t/p/w342/3apvq4tw2ogx96TOWmyTJYkko3s.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/3apvq4tw2ogx96TOWmyTJYkko3s.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/w4gXKZLfnQsQdvV1vTvdeH4ozw8.jpg"
  },
  {
    "movie_title": "Les pionniers du cinéma - ciné-concert",
    "original_title": null,
    "original_language": null,
    "director": null,
    "cast": null,
    "genre": null,
    "duration": null,
    "blurb": null,
    "source": "tmdb",
    "yt_trailer_url": null,
    "release_date": null,
    "poster_url": null,
    "poster_url_w780": null,
    "backdrop_url": null
  },
  {
    "movie_title": "On vous croit",
    "original_title": "On vous croit",
    "original_language": "fr",
    "director": "Charlotte Devillers &amp; Arnaud Dufeys",
    "cast": "Myriem Akheddiou, Laurent Capelluto",
    "genre": "Drame",
    "duration": "1h18",
    "blurb": "Aujourd'hui, Alice se retrouve devant un juge et n'a pas le droit à l'erreur. Elle doit défendre ses enfants, dont la garde est remise en cause. Pourra-t-elle les protéger de leur père avant qu'il ne soit trop tard ? Un film choc, une vraie performance. Tout public, avec avertissement.",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=Eirqx1xq2YY",
    "release_date": "2025-11-12",
    "poster_url": "https://image.tmdb.org/t/p/w342/igXPchdekOO4oKOlaatfkj04qZL.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/igXPchdekOO4oKOlaatfkj04qZL.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/cSHSViBQedLtepD4Rizq3TuBVnS.jpg"
  },
  {
    "movie_title": "Panique à Noël",
    "original_title": "Hvis ingen går i fella",
    "original_language": "no",
    "director": "Henrik Martin Dahlsbakken",
    "cast": null,
    "genre": "Animation, comédie, famille",
    "duration": "1h20",
    "blurb": "Une adorable famille de souris se prépare à célébrer Noël dans leur chaleureuse maison. Tout est prêt pour des fêtes parfaites... jusqu'à l'irruption d'intrus qui débarquent soudain. Des humains ! Pire : une famille d'humains, qui souhaitent eux aussi profiter d'un Noël à la campagne. # CIN'ESPIÈGLE En partenariat avec les Cinémas Indépendants de Bourgogne Franche-Comté (CIBFC)",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=hWyDcDSDa1A",
    "release_date": "2025-11-06",
    "poster_url": "https://image.tmdb.org/t/p/w342/fCitjmdu7gHlh4g17wkiiYmF5Zn.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/fCitjmdu7gHlh4g17wkiiYmF5Zn.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/hO7PRUf7QpCXDX1AsAZO9KM89g9.jpg"
  },
  {
    "movie_title": "Predator : badlands",
    "original_title": "Predator: Badlands",
    "original_language": "en",
    "director": "Dan Trachtenberg",
    "cast": "Elle Fanning, Stefan Grube",
    "genre": "Action, horreur",
    "duration": "1h47",
    "blurb": "Dans le futur sur une planète lointaine, un jeune Predator, exclu de son clan, trouve une alliée improbable en la personne de Thia et entreprend un voyage en territoire hostile, à la recherche de l'adversaire ultime. Attention film interdit aux moins de 12 ans. Diffusion dans le cadre du programme « Les Ambassadeurs Jeunes du Cinéma » avec les deux lycées de Château-Chinon.",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=R2n_TZgmmPo",
    "release_date": "2025-11-05",
    "poster_url": "https://image.tmdb.org/t/p/w342/empQGO0pCVTndCpihyVpNfaLebl.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/empQGO0pCVTndCpihyVpNfaLebl.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg"
  },
  {
    "movie_title": "Que la bête meure",
    "original_title": "Que la bête meure",
    "original_language": "fr",
    "director": "Claude Chabrol",
    "cast": null,
    "genre": null,
    "duration": null,
    "blurb": "Avec Caroline Cellier, Michel Duchaussoy, Jean Yanne - 1969 - Policier - 1h53 Pour venger la mort de son fils, tué par un chauffard, un homme se lance sur la piste du coupable. Il parvient bientôt à retrouver sa trace et devient un intime de sa famille. L'homme se révèle un être abject haï de tous. «Créant un climat de vengeance et de haine, Claude Chabrol va confronter deux hommes, chacun à sa manière un meurtrier, et, critiquant les mœurs modernes, aborder le thème complexe de la culpabilité.» Le Monde",
    "source": "pdf",
    "yt_trailer_url": null,
    "release_date": "1969-09-04",
    "poster_url": "https://image.tmdb.org/t/p/w342/u6EJONPP7zbzFSQwV598sg52MM5.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/u6EJONPP7zbzFSQwV598sg52MM5.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/vc9Bx0Wp7GPV6mlBdKyjjwZxZQ.jpg"
  },
  {
    "movie_title": "The neon people",
    "original_title": "The Neon People",
    "original_language": "en",
    "director": "Jean-Baptiste Thoret",
    "cast": null,
    "genre": "2025",
    "duration": "2h04",
    "blurb": "Sous le célèbre Strip de Las Vegas, des milliers de sans-abris vivent dans un immense réseau de tunnels obscurs et insalubres. The Neon People s'intéresse à une poignée d'entre eux et décrit leurs conditions de vie. Mais aussi leurs espoirs.",
    "source": "pdf",
    "yt_trailer_url": null,
    "release_date": "2024-09-15",
    "poster_url": "https://image.tmdb.org/t/p/w342/wzGPXsp0nCcwYD6i28c5a7VnRcq.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/wzGPXsp0nCcwYD6i28c5a7VnRcq.jpg",
    "backdrop_url": null
  },
  {
    "movie_title": "Vie privée",
    "original_title": "Vie privée",
    "original_language": "fr",
    "director": "Rebecca Zlotowski",
    "cast": "Jodie Foster, Daniel Auteuil, Virginie Efira",
    "genre": "Drame / Policier / Thriller",
    "duration": "1h45",
    "blurb": "Lilian Steiner est une psychiatre reconnue. Quand elle apprend la mort de l'une de ses patientes, elle se persuade qu'il s'agit d'un meurtre. Troublée, elle décide de mener son enquête. Thriller aux allures de comédie, le nouveau film de Rebecca Zlotowski « est une savoureuse fantaisie sur la psyché d'une thérapeute chamboulée s'improvisant enquêtrice. » Télérama. La grand actrice américaine Jodie Foster forme un duo épatant avec Daniel Auteuil ! DOCUMENTAIRES",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=AYYmazQVIWg",
    "release_date": "2025-09-27",
    "poster_url": "https://image.tmdb.org/t/p/w342/ySU2kboUiK2IVs9dB0w4vnPiYgk.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/ySU2kboUiK2IVs9dB0w4vnPiYgk.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/uApLc1aWuzPW6g0J6jWdmHyewHM.jpg"
  },
  {
    "movie_title": "Zootopie 2",
    "original_title": "Zootopia 2",
    "original_language": "en",
    "director": "Jared Bush &amp; Byron Howard",
    "cast": null,
    "genre": "Animation, aventure, comédie, famille",
    "duration": "1h48",
    "blurb": "Le grand retour du savoureux duo de choc des jeunes policiers Judy Hopps et Nick Wilde : ils doivent suivre la piste sinueuse d'un mystérieux reptile qui arrive à Zootopie et qui met la métropole des mammifères sens dessus dessous.",
    "source": "pdf",
    "yt_trailer_url": "https://www.youtube.com/watch?v=k0RDS4asjGg",
    "release_date": "2025-11-26",
    "poster_url": "https://image.tmdb.org/t/p/w342/8KL0XQaKDAV7KzveZzSoCZ0eaq7.jpg",
    "poster_url_w780": "https://image.tmdb.org/t/p/w780/8KL0XQaKDAV7KzveZzSoCZ0eaq7.jpg",
    "backdrop_url": "https://image.tmdb.org/t/p/w780/5h2EsPKNDdB3MAtOk9MB9Ycg9Rz.jpg"
  }
];
